PacketHeader m_header
float m_suspensionPosition[4]
float m_suspensionVelocity[4]
float m_suspensionAcceleration[4]
float m_wheelSpeed[4]
float m_wheelSlipRatio[4]
float m_wheelSlipAngle[4]
float m_wheelLatForce[4]
float m_wheelLongForce[4]
float m_heightOfCOGAboveGround
float m_localVelocityX
float m_localVelocityY
float m_localVelocityZ
float m_angularVelocityX
float m_angularVelocityY
float m_angularVelocityZ
float m_angularAccelerationX
float m_angularAccelerationY
float m_angularAccelerationZ
float m_frontWheelsAngle
float m_wheelVertForce[4]
