uint8_t m_aiControlled
uint8_t m_driverId
uint8_t m_networkId
uint8_t m_teamId
uint8_t m_myTeam
uint8_t m_raceNumber
uint8_t m_nationality
char m_name[48]
uint8_t m_yourTelemetry
uint8_t m_showOnlineNames
uint8_t m_platform
